version: "3.9"

services:
  web1:
    build:
      context: ./web
    container_name: web1
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
    restart: always

  web2:
    build:
      context: ./web
    container_name: web2
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
    restart: always

  lb:
    image: nginx:alpine
    container_name: lb
    volumes:
      - ./internal-loadbalancer/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "6767:6767"
    depends_on:
      - web1
      - web2