version: "3.9"

services:
  web1:
    build:
      context: ./web
      args:
        - VITE_SUPABASE_PROJECT_ID=${VITE_SUPABASE_PROJECT_ID}
        - VITE_SUPABASE_PUBLISHABLE_KEY=${VITE_SUPABASE_PUBLISHABLE_KEY}
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
    container_name: web1
    env_file:
      - .env
    restart: always

  web2:
    build:
      context: ./web
      args:
        - VITE_SUPABASE_PROJECT_ID=${VITE_SUPABASE_PROJECT_ID}
        - VITE_SUPABASE_PUBLISHABLE_KEY=${VITE_SUPABASE_PUBLISHABLE_KEY}
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
    container_name: web2
    env_file:
      - .env
    restart: always

  lb:
    image: nginx:alpine
    container_name: lb
    volumes:
      - ./internal-loadbalancer/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "6767:6767"
    depends_on:
      - web1
      - web2